### ISSUE TITLE
Assertion Failed: A helper named 'mut' could not be found

### ISSUE THREAD

**Issue by nagkumar** [plusacht/ember-bootstrap-datetimepicker#69]
Not working with ember 1.10.0 version.

It gives the errors

1. Assertion Failed: A helper named 'mut' could not be found
 for (action (mut time4))
2. Uncaught TypeError: this.getAttr is not a function

    inputGroupClass: computed('attrs.noIcon', function () {
      if (!this.getAttr('noIcon')) {
        return 'input-group';
      }

**Comment by jasonmit** [comment]
Master is not compatible with < 1.13

**Comment by jtabone16** [comment]
Could we install a prior version compatible with ember versions less than 1.13?
